### PR TITLE
Feat citation requests zero

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
We're only checking Crossref at the moment aren't we? If so, we should probably exclude the others.

**Comment by giorgiosironi** [comment]
Being SQL guys we understand that a `null` value would be more precise than a `0` value because if we don't check a source we should say we don't know the value rather than saying it is `0`, which is a possible result. That said the api-raml has to allow that before it can be modified here, so for the moment this is the best solution :+1:

**Comment by thewilkybarkid** [comment]
If nothing's been checked, I'd expect a `404 Not Found`. If something's been checked but has no data, I'd expect a 0 count.

(The former's as is, I'm ok with making it an empty list if the article is published though)

But yeah, merge?

**Comment by lsh-0** [comment]
> We're only checking Crossref at the moment aren't we? 

we have support for all three :) I kicked off a crossref scrape before I left and haven't done anything since. I have a ticket to add these to a cron job

**Pull request merged**
