### PR TITLE
Feature: nametrics rename

### PR DESCRIPTION
**Pull request by lsh-0**
renames `metrics` to `article_metrics` and `nametrics` to `metrics`

### CODE REVIEW

**Comment by lsh-0** [comment]
Alfred has an old database hanging around: 
```
[34.229.177.18] out: ----------
[34.229.177.18] out:           ID: configure-elife-metrics
[34.229.177.18] out:     Function: cmd.run
[34.229.177.18] out:         Name: ./install.sh && ./manage.sh collectstatic --noinput
[34.229.177.18] out:       Result: False
[34.229.177.18] out:      Comment: Command "./install.sh && ./manage.sh collectstatic --noinput" run
[34.229.177.18] out:      Started: 06:49:41.998133
[34.229.177.18] out:     Duration: 3106.467 ms
[34.229.177.18] out:      Changes:   
[34.229.177.18] out:               ----------
[34.229.177.18] out:               pid:
[34.229.177.18] out:                   3344
[34.229.177.18] out:               retcode:
[34.229.177.18] out:                   1
[34.229.177.18] out:               stderr:
[34.229.177.18] out:                   HEAD is now at 7b0bae7... Regenerated dist/
[34.229.177.18] out:                   et3 1.5 has requirement coverage==4.1, but you'll have coverage 4.5 which is incompatible.
[34.229.177.18] out:                   et3 1.5 has requirement green==2.5.0, but you'll have green 2.12.0 which is incompatible.
[34.229.177.18] out:                   Traceback (most recent call last):
[34.229.177.18] out:                     File "/srv/elife-metrics/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 62, in execute
[34.229.177.18] out:                       return self.cursor.execute(sql)
[34.229.177.18] out:                   psycopg2.ProgrammingError: relation "metrics_article" already exists
[34.229.177.18] out:                   
```

**Comment by lsh-0** [comment]
It's imposing, but it's mostly just import statements. No other logic has changed.

> It helps that the database can be regenerated from scratch (I think)

It can, but that isn't necessary. A model can specify it's table name. The models in article metrics, that used to just be metrics, explicitly state their table name. `article_metrics.models.Article` is still `metrics_article` and not `article_metrics_article`.

This would be a problem if the two apps shared models name, but that would be another problem altogether.

**Comment by lsh-0** [comment]
ah, figured it out and it's not Alfred's fault. Within the `django_migrations` table is yet another reference to the app. Updating it allows the pre-existing databases to be run. I'll add a hook to execute some sql before migration.

**Comment by lsh-0** [comment]
I've uncovered a clutch of tests that are not patched and are contacting PMC then failing non-deterministicly. I wonder if they've throttled or blacklisted the server.

**Comment by lsh-0** [comment]
the dude developing the Green test runner dismissed my suggestion of a network blocker similar to the one available to pytest: https://github.com/rob-b/pytest-blockage

I might just see if the grass really is greener on the other side ...

(bah dum tish)

**Comment by giorgiosironi** [comment]
> similar to the one available to pytest

pytest is becoming more and more ubiquitous, look at how many builds they have https://ci.appveyor.com/project/pytestbot/pytest

**Pull request merged**
